A320FailureConsole/Controllers/ACSystemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using A320FailureConsole.Models;

namespace A320FailureConsole.Controllers
{
    public class ACSystemsController : Controller
    {
        private A320FailureConsoleContext db = new A320FailureConsoleContext();

        // GET: ACSystems
        public ActionResult Index()
        {
            return View(db.ACSystems.ToList());
        }

        // GET: ACSystems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ACSystem aCSystem = db.ACSystems.Find(id);
            if (aCSystem == null)
            {
                return HttpNotFound();
            }
            return View(aCSystem);
        }

        // GET: ACSystems/Create
        //[Authorize()]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ACSystems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ACSystemID,ACSystemIDName,Description,DREF0prefix")] ACSystem aCSystem)
        {
            if (ModelState.IsValid)
            {
                db.ACSystems.Add(aCSystem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aCSystem);
        }

        // GET: ACSystems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ACSystem aCSystem = db.ACSystems.Find(id);
            if (aCSystem == null)
            {
                return HttpNotFound();
            }
            return View(aCSystem);
        }

        // POST: ACSystems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ACSystemID,ACSystemIDName,Description,DREF0prefix")] ACSystem aCSystem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aCSystem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aCSystem);
        }

        // GET: ACSystems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ACSystem aCSystem = db.ACSystems.Find(id);
            if (aCSystem == null)
            {
                return HttpNotFound();
            }
            return View(aCSystem);
        }

        // POST: ACSystems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ACSystem aCSystem = db.ACSystems.Find(id);
            db.ACSystems.Remove(aCSystem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

A320FailureConsole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - A320 Failure Console</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
 //<![CDATA[
        var tlJsHost = ((window.location.protocol == "https:") ? "https://secure.comodo.com/" : "http://www.trustlogo.com/");
        document.write(unescape("%3Cscript src='" + tlJsHost + "trustlogo/javascript/trustlogo.js' type='text/javascript'%3E%3C/script%3E"));
//]]>
    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("A320 Failure Console", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("AC Systems", "Index", "ACSystems")</li>
                    <li>@Html.ActionLink("Failures", "Index", "Failures")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - A320FailureConsole</p>
            <p><script language="JavaScript" type="text/javascript">
                TrustLogo("https://failures.pesqair.com/Content/comodo_secure_seal_100x85_transp.png", "CL1", "none");
</script>
<a href="https://www.positivessl.com/" id="comodoTL">Positive SSL</a></p>
           
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    

</body>
</html>